// components/svelte/src/Particles.svelte
<script>
    import { afterUpdate, createEventDispatcher } from "svelte";
    import { tsParticles } from "tsparticles";

    export let options = {};
    export let id = "tsparticles";
    const dispatch = createEventDispatcher();

    let oldId = id;

    afterUpdate(() => {
        if (oldId) {
            const oldContainer = tsParticles.dom().find(c => c.id === oldId);

            if (oldContainer) {
                oldContainer.destroy();
            }
        }

        if (id) {
            tsParticles.load(id, options).then((container) => {
                dispatch("particlesLoaded", {
                    particles: container
                });

                oldId = id;
            });
        } else {
            dispatch("particlesLoaded", {
                particles: undefined
            });
        }
    });
</script>

<svelte:options accessors={true}/>

<div id={id}></div>

// wrappers/react/lib/Particles.tsx
import { FC, useEffect } from "react";
import type { IParticlesProps } from "./IParticlesProps";
import type { Container } from "@tsparticles/engine";
import { engine } from "./engine";
import { useParticlesProvider } from "./ParticlesProvider";

const Particles: FC<IParticlesProps> = props => {
  const { className, id, options, particlesLoaded, style, url } = props;
  const { loaded } = useParticlesProvider();

  useEffect(() => {
    if (!loaded) {
      return;
    }

    let container: Container | undefined;

    engine.load({ id: id ?? "tsparticles", url, options }).then(c => {
      container = c;

      particlesLoaded?.(c);
    });

    return () => {
      container?.destroy();
    };
  }, [id, loaded, options, particlesLoaded, url]);

  return <div id={id ?? "tsparticles"} className={className} style={style}></div>;
};

export default Particles;
