// packages/solid/components/solid/src/IParticlesProps.ts
import type { Container, ISourceOptions } from "@tsparticles/engine";
import { JSX } from "solid-js";

export interface IParticlesProps {
    id?: string;
    width?: string;
    height?: string;
    options?: ISourceOptions;
    url?: string;
    params?: ISourceOptions;
    style?: JSX.CSSProperties;
    class?: string;
    canvasClass?: string;
    container?: { current: Container };
    // prettier-ignore
    particlesLoaded?: (container: Container) => Promise<void>;
}

// packages/react/components/react/lib/IParticlesProps.ts
import type { Container, ISourceOptions } from "@tsparticles/engine";
import type { CSSProperties } from "react";

export interface IParticlesProps {
  id?: string;
  options?: ISourceOptions;
  url?: string;
  style?: CSSProperties;
  className?: string;
  particlesLoaded?: (container?: Container) => Promise<void>;
}
