// components/svelte/src/Particles.svelte
<script>
    import { afterUpdate, createEventDispatcher } from "svelte";
    import { tsParticles } from "tsparticles";

    export let options = {};
    export let id = "tsparticles";
    const dispatch = createEventDispatcher();

    let oldId = id;

    afterUpdate(() => {
        if (oldId) {
            const oldContainer = tsParticles.dom().find(c => c.id === oldId);

            if (oldContainer) {
                oldContainer.destroy();
            }
        }

        if (id) {
            tsParticles.load(id, options).then((container) => {
                dispatch("particlesLoaded", {
                    particles: container
                });

                oldId = id;
            });
        } else {
            dispatch("particlesLoaded", {
                particles: undefined
            });
        }
    });
</script>

<svelte:options accessors={true}/>

<div id={id}></div>

// packages/react/components/react/lib/Particles.tsx
import { FC, useEffect } from "react";
import type { IParticlesProps } from "./IParticlesProps";
import { tsParticles, type Container } from "@tsparticles/engine";

const Particles: FC<IParticlesProps> = (props) => {
  const id = props.id ?? "tsparticles";

  useEffect(() => {
    let container: Container | undefined;

    tsParticles
      .load({ id, url: props.url, options: props.options })
      .then((c) => {
        container = c;

        props.particlesLoaded?.(c);
      });

    return () => {
      container?.destroy();
    };
  }, [id, props, props.url, props.options]);

  return <div id={id} className={props.className}></div>;
};

export default Particles;
