// components/svelte/src/Particles.svelte
<script lang="ts">
    import { afterUpdate, createEventDispatcher } from "svelte";
    import { Container, tsParticles } from "tsparticles";

    export let options = {};
    export let url = "";
    export let id = "tsparticles";

    const dispatch = createEventDispatcher();
    const particlesInitEvent = "particlesInit";
    const particlesLoadedEvent = "particlesLoaded";

    let oldId = id;

    afterUpdate(() => {
        tsParticles.init();

        dispatch(particlesInitEvent, tsParticles);

        if (oldId) {
            const oldContainer = tsParticles.dom().find(c => c.id === oldId);

            if (oldContainer) {
                oldContainer.destroy();
            }
        }

        if (id) {
            const cb = (container) => {
                dispatch(particlesLoadedEvent, {
                    particles: container
                });

                oldId = id;
            };

            if (url) {
                tsParticles.loadJSON(id, url).then(cb);
            } else if (options) {
                tsParticles.load(id, options).then(cb);
            } else {
                console.error('You must specify options or url to load tsParticles');
            }
        } else {
            dispatch(particlesLoadedEvent, {
                particles: undefined
            });
        }
    });
</script>

<svelte:options accessors={true}/>

<div id={id}></div>

// components/angular/projects/ng-particles/src/lib/ng-particles.component.ts
import { AfterViewInit, Component, EventEmitter, Input, Output } from '@angular/core';
import { Main, tsParticles } from 'tsparticles-core';
import type { Container } from 'tsparticles-core';
import { IParticlesProps } from './ng-particles.module';

@Component({
    selector: 'ng-particles',
    template: `
        <div [id]="id"></div> `,
    styles: [],
})
export class NgParticlesComponent implements AfterViewInit {
    @Input() options?: IParticlesProps;
    @Input() url?: string;
    @Input() id: string;
    @Output() particlesLoaded: EventEmitter<Container> = new EventEmitter<Container>();
    @Output() particlesInit: EventEmitter<Main> = new EventEmitter<Main>();

    public ngAfterViewInit(): void {
        tsParticles.init();

        this.particlesInit.emit(tsParticles);

        const cb = (container?: Container) => {
            this.particlesLoaded.emit(container);
        };

        if (this.url) {
            tsParticles.loadJSON(this.id, this.url).then(cb);
        } else if (this.options) {
            tsParticles.load(this.id, this.options).then(cb);
        } else {
            console.error('You must specify options or url to load tsParticles');
        }
    }
}

@Component({
    selector: 'Particles',
    template: `
        <div [id]="id"></div> `,
    styles: []
})
export class ParticlesComponent extends NgParticlesComponent {
    @Input() options?: IParticlesProps;
    @Input() url?: string;
    @Input() id: string;
    @Output() particlesLoaded: EventEmitter<Container> = new EventEmitter<Container>();
    @Output() particlesInit: EventEmitter<Main> = new EventEmitter<Main>();
}
