// wrappers/svelte/src/lib/Particles.svelte
<svelte:options accessors={true} />

<script lang="ts">
	import { createEventDispatcher, onDestroy, onMount } from 'svelte';
	import type { Container, ISourceOptions } from '@tsparticles/engine';
	import { tsParticles } from '@tsparticles/engine';
	import * as particlesEngineInitialization from './utils.js';

	let cssClass = '';
	export { cssClass as class };
	let mounted = false;

	let style = '';
	export { style };
	export let options: ISourceOptions = {};
	export let url = '';
	export let id = 'tsparticles';
	export let theme: string | undefined = undefined;

	const dispatch = createEventDispatcher<{
			particlesLoaded: { particles?: Container };
		}>(),
		particlesLoadedEvent = 'particlesLoaded';

	let currentContainer: Container | undefined;
	let loadGeneration = 0;

	$: if (mounted && (id || url || options)) {
		void loadParticles();
	}

	$: if (mounted && theme && currentContainer) {
		(currentContainer as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(
			theme
		);
	}

	function destroyOldContainer() {
		currentContainer?.destroy();
		currentContainer = undefined;
	}

	onDestroy(() => {
		loadGeneration++;
		destroyOldContainer();
	});

	onMount(() => {
		mounted = true;
	});

	async function loadParticles(): Promise<void> {
		const generation = ++loadGeneration;

		destroyOldContainer();

		if (!mounted) {
			return;
		}

		await particlesEngineInitialization.waitForParticlesEngineInitialization();

		if (!particlesEngineInitialization.isParticlesEngineInitialized()) {
			throw new Error(
				'initParticlesEngine(...) must be called once before rendering <Particles /> components.'
			);
		}

		if (!mounted || generation !== loadGeneration) {
			return;
		}

		if (id) {
			const cb = (container?: Container) => {
				if (generation !== loadGeneration) {
					container?.destroy();
					return;
				}

				dispatch(particlesLoadedEvent, {
					particles: container
				});
			};

			const container = await tsParticles.load({
				id,
				options,
				url
			});

			if (generation !== loadGeneration) {
				container?.destroy();
				return;
			}

			currentContainer = container;

			if (container && theme) {
				(container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(
					theme
				);
			}

			cb(container);
		} else {
			dispatch(particlesLoadedEvent, {
				particles: undefined
			});
		}
	}
</script>

<div {id} class={cssClass} {style}></div>

// wrappers/vue2/src/Particles/vue-particles.vue
<template>
  <div :id="id" />
</template>

<script lang="ts">
import { Component, Prop, Watch } from "vue-property-decorator";
import { type Container, type ISourceOptions, tsParticles } from "@tsparticles/engine";
import Vue from "vue";
import { isParticlesInitialized, waitForParticlesInitialization } from "./event-bus";

async function particlesInit(component: Particles): Promise<void> {
  if (!component.id) {
    throw new Error("Prop 'id' is required!");
  }

  const generation = component.loadGeneration;

  await waitForParticlesInitialization();

  if (!isParticlesInitialized()) {
    throw new Error(
      "@tsparticles/vue2 plugin initialization must be completed before rendering <VueParticles /> components.",
    );
  }

  const cb = (container?: Container) => {
    if (generation !== component.loadGeneration) {
      container?.destroy();
      return;
    }

    component.container = container;

    if (container && component.particlesLoaded) {
      component.particlesLoaded(container);
    }
  };

  const container = await tsParticles.load({
    id: component.id,
    options: component.options ?? {},
    url: component.url,
  });

  if (generation !== component.loadGeneration) {
    container?.destroy();
    return;
  }

  if (container && component.theme) {
    (container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(component.theme);
  }

  cb(container);
}

@Component
export default class Particles extends Vue {
  @Prop({ required: true }) readonly id!: string;
  @Prop() readonly options?: ISourceOptions;
  @Prop() readonly url?: string;
  @Prop() readonly theme?: string;
  @Prop() readonly particlesLoaded?: (container?: Container) => void;

  container?: Container;
  loadGeneration = 0;

  @Watch("options")
  @Watch("url")
  @Watch("id")
  onPropChange(): void {
    this.container?.destroy();
    this.container = undefined;
    this.loadGeneration++;
    void particlesInit(this);
  }

  @Watch("theme")
  onThemeChange(newTheme?: string): void {
    if (!this.container) return;
    (this.container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(newTheme);
  }

  mounted(): void {
    this.$nextTick(() => {
      void particlesInit(this);
    });
  }

  beforeDestroy(): void {
    this.loadGeneration++;
    this.container?.destroy();
  }
}
</script>
