// templates/scaffold/template/svelte/src/App.svelte
<script lang="ts">
  import Particles from "@tsparticles/svelte";
  import type { ISourceOptions } from "@tsparticles/engine";

  const options: ISourceOptions = {
    fullScreen: { enable: true, zIndex: -1 },
    background: { color: { value: "#1a1a2e" } },
    fpsLimit: 60,
    particles: {
      number: { value: 80, density: { enable: true } },
      color: { value: ["#6c5ce7", "#a29bfe", "#fd79a8"] },
      shape: { type: "circle" },
      opacity: { value: 0.5, random: true },
      size: { value: { min: 1, max: 4 }, random: true },
      move: {
        enable: true,
        speed: 2,
        direction: "none",
        random: false,
        straight: false,
        outModes: { default: "out" },
      },
    },
    detectRetina: true,
  };
</script>

<div id="app-content">
  <h1>Hello, tsParticles!</h1>
</div>
<Particles id="tsparticles" options={options} />

<style>
  :global(body) {
    margin: 0;
    overflow: hidden;
    font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  }

  #app-content {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 10;
    text-align: center;
    color: #fff;
    pointer-events: none;
  }

  h1 {
    font-size: 3.2em;
    text-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  }
</style>

// templates/particles/template/nuxt3/app.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { loadParticles } from "@tsparticles/particles";
import { tsParticles } from "@tsparticles/engine";
import type { ISourceOptions } from "@tsparticles/engine";

const options: ISourceOptions = {
  background: { color: { value: "#0d0d2b" } },
  fpsLimit: 120,
  particles: {
    number: { value: 80, density: { enable: true } },
    color: { value: "#ffffff" },
    shape: { type: "circle" },
    opacity: { value: 0.5 },
    size: { value: { min: 1, max: 5 } },
    links: { enable: true, distance: 150, color: "#ffffff", opacity: 0.3, width: 1 },
    move: { enable: true, speed: 2, direction: "none", random: false, straight: false, outModes: { default: "bounce" } },
  },
  interactivity: {
    events: { onHover: { enable: true, mode: "repulse" }, onClick: { enable: true, mode: "push" } },
    modes: { repulse: { distance: 100, duration: 0.4 }, push: { quantity: 4 } },
  },
  detectRetina: true,
};

onMounted(() => {
  void loadParticles(tsParticles);
});
</script>

<template>
  <div>
    <div id="app">
      <h1>tsParticles</h1>
    </div>
    <vue-particles id="tsparticles" :options="options" />
  </div>
</template>

<style>
body {
  margin: 0;
  overflow: hidden;
}

#app {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 10;
  text-align: center;
  color: #fff;
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  pointer-events: none;
}

h1 {
  font-size: 3.2em;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
}
</style>
