// components/solid/src/Particles.tsx
import { tsParticles, Container } from "tsparticles";
import type { IParticlesProps } from "./IParticlesProps";
import {
	createEffect,
	createMemo,
	createSignal,
	onCleanup,
	JSX,
} from "solid-js";

interface MutableRefObject<T> {
	current: T | null;
}

/**
 * @param (props:IParticlesProps) Particles component properties
 */
const Particles = (props: IParticlesProps): JSX.Element => {
	try {
		const id = props.id ?? "tsparticles";

		if (props.init) {
			props.init(tsParticles);
		}

		const options = createMemo(() => props.params ?? props.options ?? {});

		const refContainer = props.container as MutableRefObject<
			Container | undefined
		>;
		const { className, canvasClassName, loaded, url, width, height } = props;
		const [containerId, setContainerId] = createSignal(
			undefined as string | undefined
		);

		const cb = (container?: Container) => {
			if (refContainer) {
				refContainer.current = container;
			}

			setContainerId(container?.id);

			if (loaded && container) {
				loaded(container);
			}
		};

		createEffect(() => {
			const container = tsParticles.dom().find((t) => t.id === containerId());

			container?.destroy();

			if (url) {
				tsParticles.loadJSON(id, url).then(cb);
			} else {
				tsParticles.load(id, options()).then(cb);
			}
		});

		onCleanup(() => {
			const container = tsParticles.dom().find((t) => t.id === containerId());

			container?.destroy();

			setContainerId(undefined);
		});

		return (
			<div className={className ?? ""} id={id}>
				<canvas
					className={canvasClassName ?? ""}
					style={{
						...props.style,
						width,
						height,
					}}
				/>
			</div>
		);
	} catch (e) {
		return <div></div>;
	}
};

export default Particles;

// components/inferno/src/Particles.tsx
import { Component, InfernoNode } from "inferno";
import equal from "fast-deep-equal/react";
import { tsParticles, Container } from "tsparticles-engine";
import type { IParticlesProps } from "./IParticlesProps";
import type { IParticlesState } from "./IParticlesState";

interface MutableRefObject<T> {
	current: T | null;
}

/**
 * @param {IParticlesProps}
 */
export default class Particles extends Component<
	IParticlesProps,
	IParticlesState
> {
	static defaultProps: IParticlesProps = {
		width: "100%",
		height: "100%",
		options: {},
		style: {},
		id: "tsparticles",
	};

	constructor(props: IParticlesProps) {
		super(props);

		this.state = {
			library: undefined,
		};
	}

	destroy(): void {
		if (!this.state.library) {
			return;
		}

		this.state.library.destroy();

		this.setState({
			library: undefined,
		});
	}

	shouldComponentUpdate(nextProps: Readonly<IParticlesProps>): boolean {
		return !equal(nextProps, this.props);
	}

	componentDidUpdate(): void {
		this.refresh();
	}

	forceUpdate(): void {
		this.refresh();

		super.forceUpdate();
	}

	componentDidMount(): void {
		(async () => {
			if (this.props.init) {
				await this.props.init(tsParticles);
			}

			this.loadParticles();
		})();
	}

	componentWillUnmount(): void {
		this.destroy();
	}

	render(): InfernoNode {
		const { width, height, className, canvasClassName, id } = this.props;

		return (
			<div className={className} id={id}>
				<canvas
					className={canvasClassName}
					style={{
						...this.props.style,
						width,
						height,
					}}
				/>
			</div>
		);
	}

	private refresh(): void {
		this.destroy();

		this.loadParticles();
	}

	private loadParticles(): void {
		const cb = async (container?: Container) => {
			if (this.props.container) {
				(this.props.container as MutableRefObject<Container>).current =
					container;
			}

			this.setState({
				library: container,
			});

			if (this.props.loaded) {
				await this.props.loaded(container);
			}
		};

		if (this.props.url) {
			tsParticles.loadJSON(this.props.id, this.props.url).then(cb);
		} else {
			tsParticles
				.load(this.props.id, this.props.params ?? this.props.options)
				.then(cb);
		}
	}
}
