// components/react-alt/src/IParticlesProps.ts
import type { RefObject } from "react";
import type { Container, ISourceOptions, Engine } from "tsparticles-engine";
import type { CSSProperties } from "react";

export interface IParticlesProps {
    id?: string;
    width?: string;
    height?: string;
    options?: ISourceOptions;
    params?: ISourceOptions;
    url?: string;
    style?: CSSProperties;
    className?: string;
    canvasClassName?: string;
    container?: RefObject<Container>;
    init?: (engine: Engine) => Promise<void>;
    loaded?: (container?: Container) => Promise<void>;
}

// packages/qwik/src/components/particles/IParticlesProps.ts
import {
  CSSProperties, ClassList, NoSerialize, QRL, Signal
} from "@builder.io/qwik";
import type { Container, Engine, ISourceOptions } from "tsparticles-engine";

export interface IParticlesProps {
	id?: string;
	width?: number | string;
	height?: number | string;
	options?: ISourceOptions;
	url?: string;
	params?: ISourceOptions;
	style?: CSSProperties;
	class?: ClassList | Signal<ClassList>;
	canvasClassName?: ClassList | Signal<ClassList>;
	container?: Signal<NoSerialize<Container | undefined>>;
	init?: QRL<(engine: Engine) => Promise<void>>;
	loaded?: QRL<(container?: Container) => Promise<void>>;
}
