// packages/solid/components/solid/src/Particles.tsx
import { tsParticles } from "@tsparticles/engine";
import { createEffect, createResource, JSX, mergeProps, on, onCleanup, onMount } from "solid-js";
import type { IParticlesProps } from "./IParticlesProps";

/**
 * @param (props:IParticlesProps) Particles component properties
 */
const Particles = (props: IParticlesProps): JSX.Element => {
    const config = mergeProps({ id: "tsparticles" }, props);

    onMount(() => {
        const [container] = createResource(
            () => ({
                id: config.id,
                options: config.params ?? config.options ?? {},
                url: config.url,
            }),
            data => tsParticles.load(data),
        );

        createEffect(
            on(container, container => {
                if (!container) return;
                config.particlesLoaded?.(container);
                onCleanup(() => container.destroy());
            }),
        );
    });

    return (
        <div class={config.class} id={config.id}>
            <canvas
                class={config.canvasClass}
                style={{
                    ...config.style,
                    width: config.width,
                    height: config.height,
                }}
            />
        </div>
    );
};

export default Particles;

// packages/qwik/src/components/particles/particles.tsx
import {
  $,
  NoSerialize,
  component$,
  noSerialize,
  useSignal,
  useVisibleTask$,
} from "@builder.io/qwik";
import { Container, tsParticles } from "tsparticles-engine";
import type { IParticlesProps } from "./IParticlesProps";

/**
 * @param (props:IParticlesProps) Particles component properties
 */
const Particles = component$<IParticlesProps>((props) => {
  const initSig = useSignal(false);

  const librarySig = useSignal<NoSerialize<Container | undefined>>(undefined);

  const id = props.id ?? "tsparticles";

  const {
    init: InitFC,
    class: className,
    canvasClassName,
    height,
    width,
    loaded,
  } = props;

  useVisibleTask$(function Initializer({ track, cleanup }) {
    track(() => initSig.value);

    const loadParticles = $(async () => {
      if (!initSig.value) return;

      const container = await tsParticles.load({
        url: props.url,
        id,
        options: props.options ?? props.params,
      });

      if (props.container) {
        props.container.value = noSerialize(container);
      }

      librarySig.value = noSerialize(container);

      if (loaded) {
        await loaded(container);
      }
    });

    const initParticles = async () => {
      if (InitFC) {
        await InitFC(tsParticles);
      }

      initSig.value = true;
      await loadParticles();
    };

    initParticles();

    cleanup(() => {
      if (librarySig.value) {
        librarySig.value.destroy();
        librarySig.value = undefined;
      }
    });
  });

  return (
    <div class={className} id={id}>
      <canvas
        class={canvasClassName}
        height={height}
        width={width}
        style={{
          ...props.style,
        }}
      />
    </div>
  );
});

export default Particles;
