// wrappers/preact/src/Particles.tsx
import { Component } from "preact/compat";
import { ComponentChild } from "preact";
import { tsParticles, Container } from "@tsparticles/engine";
import type { IParticlesProps } from "./IParticlesProps";
import type { IParticlesState } from "./IParticlesState";
import { MutableRefObject } from "react";
import { deepCompare } from "./Utils";
import React from "preact/compat";
import { isParticlesEngineInitialized, waitForParticlesEngineInitialization } from "./initParticlesEngine";

/**
 * @param {IParticlesProps}
 */
export default class Particles extends Component<IParticlesProps, IParticlesState> {
  static defaultProps: IParticlesProps = {
    width: "100%",
    height: "100%",
    options: {},
    style: {},
    id: "tsparticles",
  };

  constructor(props: IParticlesProps) {
    super(props);

    this.state = {
      init: isParticlesEngineInitialized(),
      library: undefined,
    };
  }

  destroy(): void {
    if (!this.state.library) {
      return;
    }

    this.state.library.destroy();

    this.setState({
      library: undefined,
    });
  }

  shouldComponentUpdate(nextProps: Readonly<IParticlesProps>, nextState: Readonly<IParticlesState>): boolean {
    return (
      nextState.init !== this.state.init ||
      nextProps.url !== this.props.url ||
      nextProps.id !== this.props.id ||
      nextProps.canvasClassName !== this.props.canvasClassName ||
      nextProps.className !== this.props.className ||
      nextProps.height !== this.props.height ||
      nextProps.width !== this.props.width ||
      !deepCompare(nextProps.style, this.props.style) ||
      nextProps.particlesLoaded !== this.props.particlesLoaded ||
      nextProps.theme !== this.props.theme ||
      !deepCompare(nextProps.options ?? nextProps.params, this.props.options ?? this.props.params, key =>
        key.startsWith("_"),
      )
    );
  }

  componentDidUpdate(prevProps: Readonly<IParticlesProps>): void {
    if (prevProps.theme !== this.props.theme && this.state.library) {
      void (this.state.library as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(
        this.props.theme,
      );
    }

    if (
      !this.state.library ||
      prevProps.url !== this.props.url ||
      prevProps.id !== this.props.id ||
      prevProps.canvasClassName !== this.props.canvasClassName ||
      prevProps.className !== this.props.className ||
      prevProps.height !== this.props.height ||
      prevProps.width !== this.props.width ||
      !deepCompare(prevProps.style, this.props.style) ||
      prevProps.particlesLoaded !== this.props.particlesLoaded ||
      !deepCompare(prevProps.options ?? prevProps.params, this.props.options ?? this.props.params, key =>
        key.startsWith("_"),
      )
    ) {
      this.refresh();
    }
  }

  forceUpdate(): void {
    this.refresh().then(() => {
      super.forceUpdate();
    });
  }

  componentDidMount(): void {
    (async () => {
      if (!this.state.init) {
        await waitForParticlesEngineInitialization();

        if (!isParticlesEngineInitialized()) {
          throw new Error("initParticlesEngine(...) must be called once before rendering <Particles /> components.");
        }
      }

      this.setState(
        {
          init: true,
        },
        () => {
          void this.loadParticles();
        },
      );
    })();
  }

  componentWillUnmount(): void {
    this.destroy();
  }

  render(): ComponentChild {
    const { width, height, className, canvasClassName, id } = this.props;

    return (
      <div className={className} id={id}>
        <canvas
          className={canvasClassName}
          style={{
            ...this.props.style,
            width,
            height,
          }}
        />
      </div>
    );
  }

  private async refresh(): Promise<void> {
    this.destroy();

    await this.loadParticles();
  }

  private async loadParticles(): Promise<void> {
    if (!this.state.init) {
      return;
    }

    const cb = async (container?: Container) => {
      if (this.props.container) {
        (this.props.container as MutableRefObject<Container | undefined>).current = container;
      }

      this.setState({
        library: container,
      });

      if (container && this.props.theme) {
        await (container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(this.props.theme);
      }

      if (this.props.particlesLoaded) {
        await this.props.particlesLoaded(container);
      }
    };

    const container = await tsParticles.load({
      url: this.props.url,
      options: this.props.options,
      id: this.props.id,
    });

    await cb(container);
  }
}

// wrappers/solid/src/Particles.tsx
import { tsParticles, type Container } from "@tsparticles/engine";
import { createEffect, createMemo, JSX, mergeProps, onCleanup } from "solid-js";
import type { IParticlesProps } from "./IParticlesProps";
import { isParticlesEngineInitialized, waitForParticlesEngineInitialization } from "./initParticlesEngine";

const Particles = (props: IParticlesProps): JSX.Element => {
  const merged = mergeProps({ id: "tsparticles" }, props);

  let container: Container | undefined;
  let loadId = 0;

  const loadParams = createMemo(() => ({
    id: props.id ?? "tsparticles",
    options: props.options ?? props.params,
    url: props.url,
  }));

  createEffect(() => {
    const { id, options, url } = loadParams();
    const currentLoadId = ++loadId;

    void (async () => {
      container?.destroy();

      await waitForParticlesEngineInitialization();

      if (!isParticlesEngineInitialized()) {
        throw new Error("initParticlesEngine(...) must be called once before rendering <Particles /> components.");
      }

      const newContainer = await tsParticles.load({ id, options, url });

      if (currentLoadId !== loadId) {
        newContainer?.destroy();
        return;
      }

      container = newContainer;

      props.particlesLoaded?.(container);
    })();
  });

  createEffect(() => {
    const theme = props.theme;

    if (!container || !theme) return;
    (container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(theme);
  });

  onCleanup(() => {
    container?.destroy();
  });

  return (
    <div class={merged.class} id={merged.id}>
      <canvas
        class={merged.canvasClass}
        style={{
          ...merged.style,
          width: merged.width,
          height: merged.height,
        }}
      />
    </div>
  );
};

export default Particles;
