// wrappers/svelte/src/lib/Particles.svelte
<svelte:options accessors={true} />

<script lang="ts">
	import { createEventDispatcher, onDestroy, onMount } from 'svelte';
	import type { Container, ISourceOptions } from '@tsparticles/engine';
	import { tsParticles } from '@tsparticles/engine';
	import * as particlesEngineInitialization from './utils.js';

	let cssClass = '';
	export { cssClass as class };
	let mounted = false;

	let style = '';
	export { style };
	export let options: ISourceOptions = {};
	export let url = '';
	export let id = 'tsparticles';
	export let theme: string | undefined = undefined;

	const dispatch = createEventDispatcher<{
			particlesLoaded: { particles?: Container };
		}>(),
		particlesLoadedEvent = 'particlesLoaded';

	let currentContainer: Container | undefined;

	$: if (mounted && (id || url || options)) {
		void loadParticles();
	}

	$: if (mounted && theme && currentContainer) {
		(currentContainer as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(
			theme
		);
	}

	function destroyOldContainer() {
		currentContainer?.destroy();
		currentContainer = undefined;
	}

	onDestroy(() => {
		destroyOldContainer();
	});

	onMount(() => {
		mounted = true;
	});

	async function loadParticles(): Promise<void> {
		destroyOldContainer();

		if (!mounted) {
			return;
		}

		await particlesEngineInitialization.waitForParticlesEngineInitialization();

		if (!particlesEngineInitialization.isParticlesEngineInitialized()) {
			throw new Error(
				'initParticlesEngine(...) must be called once before rendering <Particles /> components.'
			);
		}

		if (!mounted) {
			return;
		}

		if (id) {
			const cb = (container?: Container) => {
				dispatch(particlesLoadedEvent, {
					particles: container
				});
			};

			const container = await tsParticles.load({
				id,
				options,
				url
			});

			currentContainer = container;

			if (container && theme) {
				(container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(
					theme
				);
			}

			cb(container);
		} else {
			dispatch(particlesLoadedEvent, {
				particles: undefined
			});
		}
	}
</script>

<div {id} class={cssClass} {style}></div>

// wrappers/solid/src/Particles.tsx
import { tsParticles, type Container } from "@tsparticles/engine";
import { createEffect, createMemo, JSX, mergeProps, onCleanup } from "solid-js";
import type { IParticlesProps } from "./IParticlesProps";
import { isParticlesEngineInitialized, waitForParticlesEngineInitialization } from "./initParticlesEngine";

const Particles = (props: IParticlesProps): JSX.Element => {
  const merged = mergeProps({ id: "tsparticles" }, props);

  let container: Container | undefined;
  let loadId = 0;

  const loadParams = createMemo(() => ({
    id: props.id ?? "tsparticles",
    options: props.options ?? props.params,
    url: props.url,
  }));

  createEffect(() => {
    const { id, options, url } = loadParams();
    const currentLoadId = ++loadId;

    void (async () => {
      container?.destroy();

      await waitForParticlesEngineInitialization();

      if (!isParticlesEngineInitialized()) {
        throw new Error("initParticlesEngine(...) must be called once before rendering <Particles /> components.");
      }

      const newContainer = await tsParticles.load({ id, options, url });

      if (currentLoadId !== loadId) {
        newContainer?.destroy();
        return;
      }

      container = newContainer;

      props.particlesLoaded?.(container);
    })();
  });

  createEffect(() => {
    const theme = props.theme;

    if (!container || !theme) return;
    (container as unknown as { loadTheme?: (name?: string) => Promise<void> }).loadTheme?.(theme);
  });

  onCleanup(() => {
    container?.destroy();
  });

  return (
    <div class={merged.class} id={merged.id}>
      <canvas
        class={merged.canvasClass}
        style={{
          ...merged.style,
          width: merged.width,
          height: merged.height,
        }}
      />
    </div>
  );
};

export default Particles;
